### ISSUE TITLE
Could not compile `mysqlclient-sys`.

### ISSUE THREAD

**Issue by Sjoerrdd** [diesel-rs/diesel#1608]
Hello,
I want to connect to a mysql database, but I'm getting the following error:

```
   Compiling mysqlclient-sys v0.2.3
error: could not find native static library `mysqlclient`, perhaps an -L flag is missing?

error: Could not compile `mysqlclient-sys`.

To learn more, run the command again with --verbose.
```

### Versions

- **Rust:**  1.26.0 nightly
- **Diesel:** 1.1.1
- **Database:**  MySQL 5.7.0
- **Operating System** Windows 10

### Steps to reproduce
Cargo.toml:
```
[package]
name = "poll"
version = "0.1.0"
authors = ["Gebruiker"]

[dependencies]
rocket = "0.3.6"
rocket_codegen = "0.3.6"
diesel = { version = "1.1.1", features = ["mysql"] }
dotenv = "0.9.0"
```

** #1286 does not solve the issue for me **

**Comment by sgrif** [comment]
Please have a look at the readme of that crate (https://github.com/sgrif/mysqlclient-sys). If you are still having issues, please open an issue over there.

**Comment by NotIntMan** [comment]
I got the same problem while installing `diesel_cli`.
```
> cargo install diesel_cli
    Updating crates.io index
  Installing diesel_cli v1.4.0
   Compiling proc-macro2 v0.4.27
   ...
   Compiling mysqlclient-sys v0.2.4
   Compiling pq-sys v0.4.6
   Compiling thread_local v0.3.6
   Compiling textwrap v0.10.0
   Compiling rand_isaac v0.1.1
   Compiling rand_xorshift v0.1.1
   Compiling rand_hc v0.1.0
   Compiling syn v0.11.11
   Compiling aho-corasick v0.6.10
   Compiling quote v0.6.11
   Compiling idna v0.1.5
error: could not find native static library `mysqlclient`, perhaps an -L flag is missing?

error: aborting due to previous error

error: Could not compile `mysqlclient-sys`.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `diesel_cli v1.4.0`, intermediate artifacts can be found at `C:\Users\D77CB~1.DEM\AppData\Local\Temp\cargo-install2PGYJy`

Caused by:
  build failed
```

Does this problem solved by anyone? Please, help.

**Comment by weiznich** [comment]
@NotIntMan You are missing [libmysqlclient](https://dev.mysql.com/downloads/connector/c/). Probably you need to set an environment variable to point to the right directory, but I'm not sure about that (I'm not using windows 🤷‍♂️ ). See the [documentation of mysqlclient-sys](https://github.com/sgrif/mysqlclient-sys) for details

**Comment by liuspatt** [comment]
For windows install https://downloads.mysql.com/archives/c-c/
set 
`setx MYSQLCLIENT_LIB_DIR "C:\Program Files\MySQL\MySQL Connector C 6.1\lib\vs14"`
run 
`cargo install diesel_cli --no-default-features --features mysql`

**Comment by youngtrashbag** [comment]
@liuspatt thank man, it worked 😄

**Comment by SaintGuacamole** [comment]
For everyone on Windows that has WSL2.
The mysqlclient is still not working on the Windows Commandline, but opening an ubuntu command line & running `apt-get install libmysqlclient-dev` followed by `cargo install diesel_cli` did the trick for me.

**Comment by Luberski** [comment]
@liuspatt How did you know to use this exact name of env variable "MYSQLCLIENT_LIB_DIR"? I'm asking because doing it in path variable results in error.

**Comment by DehaiWang** [comment]
@liuspatt  not work in windows 10,
error: failed to run custom build command for `mysqlclient-sys v0.4.0`

**Comment by davidkhala** [comment]
> @liuspatt not work in windows 10, error: failed to run custom build command for `mysqlclient-sys v0.4.0`

I have the same problem

**Comment by wgx-user** [comment]
> @liuspatt thank man, it worked 😄请问你是怎么解决的呀

**Comment by wgx-user** [comment]
你解决了嘛

**Comment by KianBrose** [comment]
Still not working

**Comment by wgx-user** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by MalongGuo** [comment]
![image](https://github.com/user-attachments/assets/aa83cba2-9400-4112-a7fa-d30c8efedad1)
export LDFLAGS="-L/usr/local/opt/mysql-client@8.0/lib"

**Comment by huedaya** [comment]
This is works for me after reading the https://github.com/sgrif/mysqlclient-sys/blob/master/README.md#building readme.

```Dockerfile
# Using the `rust-musl-builder` as base image, instead of
# the official Rust toolchain
FROM clux/muslrust:stable AS chef
USER root
# Install libmysqlclient for diesel support
RUN apt-get update && apt-get install -y \
    libmysqlclient-dev \
    pkg-config \
    mysql-client \
    && rm -rf /var/lib/apt/lists/*

...
```

**Comment by wgx-user** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
